root = "."
tmp_dir = "bin"

[build]
  cmd = "go build -o ./bin/snagarr ./cmd/snagarr"
  bin = "./bin/snagarr"
  args_bin = ["serve"]
  include_ext = ["go", "sql"]
  exclude_dir = ["web", "dist", "bin", "tmp", "data", "node_modules", ".venv", ".ven", ".idea", ".stfolder", "website"]
  exclude_regex = ["_test\\.go"]
  delay = 300
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true

[misc]
  clean_on_exit = true
